sudo: required

services:
  - docker
before_install:
   - docker build -t flyters33/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true flyters33/react-test npm test
after_success:
  - docker build -t flyters633/multi-client ./client
  - docker build -t flyters633/multi-nginx ./nginx
  - docker build -t flyters633/multi-worker ./worker
  - docker build -t flyters633/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push flyters633/multi-client
  - docker push flyters633/multi-nginx
  - docker push flyters633/multi-server
  - docker push flyters633/multi-worker
